### ISSUE TITLE
Why locators are not shown as class variable?

### ISSUE THREAD

**Issue by shinobi01** [NayakwadiS/selenium-page-factory#14]
Thank you for providing such nice features. I have a questions on using it, I got the template from the introduction documents
https://selenium-page-factory.readthedocs.io/en/latest/#python-pytest
but the 'edtUserName' or 'edtPassword' are not shown as class variable, when I typing 'self.edt...' the 'edtUserName' and 'edtpasswond' are not shown in candidates. 
Did I miss something to use PageFactory?
![image](https://user-images.githubusercontent.com/19482522/185830818-1c504b8e-1ce4-444c-bab2-c1855c9af8bd.png)

**Comment by NayakwadiS** [comment]
Here Class variables are considered as webelements and are created at run time.
[Documentation ](https://selenium-page-factory.readthedocs.io/en/latest/#extended-webelements-methods) 
Thus those are not available in suggestions list.
Thanks.

**Comment by shinobi01** [comment]
Thank you for your comments.
