### ISSUE TITLE
It is impossible to read text from an element that is initially hidden on the web page

### ISSUE THREAD

**Issue by randygschmidt** [NayakwadiS/selenium-page-factory#7]
The web page has elements via XPATH until text (in case of password) or an error occurs (such as an illegal password). I am unable to read the displayed text for the web element (using get_text()) or click the element (a show password button) since they are initially hidden when the web page is displayed and the page factory object is instantiated.

I can rely on using Selenium directly but would be a nice feature to be able to rescan the locators to find the new elements that are visible.

**Comment by NayakwadiS** [comment]
When error occurs (such as an illegal password), if you add/update  elements in `locators = { }` dictionary in your page class it will rescan the locators at run time.
