### ISSUE TITLE
Request: add support for mobile testing

### ISSUE THREAD

**Issue by apiliguzov** [NayakwadiS/selenium-page-factory#9]
It would be great to have the support for mobile testing methods, such as
driver.find_element_by_ios_uiautomation()
driver.find_element_by_accessibility_id()
driver.find_element_by_android_uiautomator()

**Comment by NayakwadiS** [comment]
#11 Added support to `driver.find_element_by_accessibility_id()`
initialize your test with `self.mobile_test = True` 
or 
you can also use old way of creating webElement with change in locator dictionary as below eg -
```
locators = {
"btnSignOn": ('ID', 'com.carezone.caredroid.careapp.medications:id/welcome_page_sign_bton'),
}
```
